root = "."
tmp_dir = "tmp"

[build]
  args_bin = ["run", "./main.go"]
  delay = 1500
  exclude_dir = ["tmp"]
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  include_ext = ["go", "html", "tmpl", "css", "png"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  build = "yellow"
  main = "orange"
  runner = "greener"
  watcher = "cyan"

[log]
  time = true

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false